#!/data/data/com.termux/files/usr/bin/bash
set -u

# Hotfix v2 for Huawei/Kirin/Mali/Maleoon + Termux:X11 + XFCE.
# Goal:
#   1) keep XFCE stable on Termux:X11;
#   2) run virglrenderer-android cleanly, without inheriting zink/virpipe env;
#   3) stop Firefox from killing the session through VirGL/WebGL;
#   4) keep explicit VirGL test wrappers for apps that actually need GPU.

PREFIX="${PREFIX:-/data/data/com.termux/files/usr}"
HOME="${HOME:-/data/data/com.termux/files/home}"
TERMUX_TMP="${TMPDIR:-$PREFIX/tmp}"
mkdir -p "$HOME/.config" "$HOME/bin" "$HOME/Desktop" "$HOME/.local/share/applications" "$TERMUX_TMP"

info() { printf '\033[0;36m[*]\033[0m %s\n' "$*"; }
ok()   { printf '\033[0;32m[+]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$*"; }

info "Stopping old X11/VirGL/XFCE processes..."
pkill -9 -f "virgl_test_server" 2>/dev/null || true
pkill -9 -f "termux.x11" 2>/dev/null || true
pkill -9 -f "Xvnc" 2>/dev/null || true
pkill -9 -f "xfce4-session" 2>/dev/null || true
pkill -9 -f "xfwm4" 2>/dev/null || true
pkill -9 -f "xfdesktop" 2>/dev/null || true
pkill -9 -f "firefox" 2>/dev/null || true
pkill -9 -f "dbus" 2>/dev/null || true
rm -f /tmp/.X0-lock /tmp/.X1-lock /tmp/.X11-unix/X0 /tmp/.X11-unix/X1 \
      "$TERMUX_TMP"/.virgl_test "$TERMUX_TMP"/virgl_test* 2>/dev/null || true

info "Installing/refreshing required packages where available..."
apt-get update -y >/dev/null 2>&1 || true
apt-get install -y virglrenderer-android angle-android dbus-x11 mesa-utils >/dev/null 2>&1 || true

info "Writing clean Kirin/Mali GPU environment..."
cat > "$HOME/.config/linux-gpu.sh" <<'GPUCFG'
# Generated by termux-kirin-x11-hotfix-v2.sh
# Client-side OpenGL path for Huawei/Kirin/Mali/Maleoon.
# Do NOT use native zink here: Mali/Maleoon Vulkan path is unstable in Termux:X11.
export TERMUX_GPU_PROFILE="mali_virgl"
export TERMUX_GPU_LABEL="Huawei/Kirin/Mali/Maleoon via VirGL/virpipe"
export MESA_NO_ERROR=1
export MESA_GL_VERSION_OVERRIDE=4.0
export MESA_GLES_VERSION_OVERRIDE=3.2
export GALLIUM_DRIVER=virpipe
export LIBGL_DRI3_DISABLE=1
export MESA_SHADER_CACHE_DISABLE=false
export XDG_DATA_DIRS=/data/data/com.termux/files/usr/share:${XDG_DATA_DIRS:-}
export XDG_CONFIG_DIRS=/data/data/com.termux/files/usr/etc/xdg:${XDG_CONFIG_DIRS:-}
unset MESA_LOADER_DRIVER_OVERRIDE
unset VK_ICD_FILENAMES
unset TU_DEBUG
unset ZINK_DESCRIPTORS
unset MESA_VK_WSI_PRESENT_MODE
unset LIBGL_ALWAYS_SOFTWARE
GPUCFG

info "Writing VirGL helper with clean server environment..."
cat > "$HOME/.config/termux-gpu-common.sh" <<'GPUCOMMON'
#!/data/data/com.termux/files/usr/bin/bash
PREFIX="${PREFIX:-/data/data/com.termux/files/usr}"
TERMUX_TMP="${TMPDIR:-$PREFIX/tmp}"
mkdir -p "$TERMUX_TMP"

choose_virgl_args() {
    local mode="${TERMUX_VIRGL_BACKEND:-angle}"
    local help_text
    help_text="$(virgl_test_server_android --help 2>&1 || true)"

    case "$mode" in
        angle)
            echo "$help_text" | grep -q -- '--angle-gl' && { printf '%s' '--angle-gl'; return; }
            ;;
        surfaceless)
            echo "$help_text" | grep -q -- '--use-egl-surfaceless' && { printf '%s' '--use-egl-surfaceless'; return; }
            ;;
        plain)
            printf '%s' ''
            return
            ;;
    esac

    # Conservative fallback: plain Android GLES backend.
    printf '%s' ''
}

start_virgl_server() {
    command -v virgl_test_server_android >/dev/null 2>&1 || {
        echo "[!] virgl_test_server_android not found. Try: pkg install virglrenderer-android"
        return 1
    }

    if pgrep -f "virgl_test_server_android" >/dev/null 2>&1; then
        return 0
    fi

    local log="$TERMUX_TMP/virgl-kirin.log"
    local args
    args="$(choose_virgl_args)"

    echo "[*] Starting VirGL Android renderer for Kirin/Mali... backend='${TERMUX_VIRGL_BACKEND:-angle}', args='$args', log: $log"
    (
        while true; do
            {
                echo "[$(date)] start virgl_test_server_android $args"
                echo "[$(date)] server env is intentionally cleaned from Mesa/Zink/Gallium variables"
            } >> "$log"

            # Important: the SERVER must not inherit client-side GALLIUM_DRIVER=virpipe
            # and must not inherit old zink/vulkan variables. Otherwise it can recurse or
            # try the broken Mali/Maleoon Zink path.
            env \
                -u GALLIUM_DRIVER \
                -u MESA_LOADER_DRIVER_OVERRIDE \
                -u VK_ICD_FILENAMES \
                -u TU_DEBUG \
                -u ZINK_DESCRIPTORS \
                -u MESA_VK_WSI_PRESENT_MODE \
                -u MESA_GL_VERSION_OVERRIDE \
                -u MESA_GLES_VERSION_OVERRIDE \
                -u LIBGL_ALWAYS_SOFTWARE \
                HOME="$HOME" PREFIX="$PREFIX" TMPDIR="$TERMUX_TMP" PATH="$PATH" \
                virgl_test_server_android $args >> "$log" 2>&1

            echo "[$(date)] VirGL exited; restarting in 2s" >> "$log"
            sleep 2
        done
    ) &
    echo $! > "$TERMUX_TMP/virgl-watchdog.pid"
    sleep 1
}

stop_virgl_server() {
    [ -f "$TERMUX_TMP/virgl-watchdog.pid" ] && kill "$(cat "$TERMUX_TMP/virgl-watchdog.pid")" 2>/dev/null || true
    rm -f "$TERMUX_TMP/virgl-watchdog.pid" 2>/dev/null || true
    pkill -f "virgl_test_server_android" 2>/dev/null || true
}
GPUCOMMON
chmod +x "$HOME/.config/termux-gpu-common.sh"

info "Disabling XFCE session restore/compositor, clearing restored clients..."
mkdir -p "$HOME/.config/xfce4/xfconf/xfce-perchannel-xml" "$HOME/.cache/sessions" "$HOME/.config/autostart"
rm -rf "$HOME/.cache/sessions"/* 2>/dev/null || true
cat > "$HOME/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml" <<'XFCESESSION'
<?xml version="1.0" encoding="UTF-8"?>
<channel name="xfce4-session" version="1.0">
  <property name="general" type="empty">
    <property name="SaveOnExit" type="bool" value="false"/>
  </property>
</channel>
XFCESESSION
cat > "$HOME/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml" <<'XFWM'
<?xml version="1.0" encoding="UTF-8"?>
<channel name="xfwm4" version="1.0">
  <property name="general" type="empty">
    <property name="use_compositing" type="bool" value="false"/>
    <property name="frame_opacity" type="int" value="100"/>
    <property name="inactive_opacity" type="int" value="100"/>
    <property name="popup_opacity" type="int" value="100"/>
    <property name="show_frame_shadow" type="bool" value="false"/>
    <property name="show_popup_shadow" type="bool" value="false"/>
    <property name="theme" type="string" value="Default-xhdpi"/>
  </property>
</channel>
XFWM

# Fix the earlier hardcoded /root first-run path if it exists.
cat > "$HOME/.config/autostart/xfce-first-run.desktop" <<'FIRSTRUN'
[Desktop Entry]
Type=Application
Name=XFCE First Run Setup
Exec=sh -c 'test -x "$HOME/.config/xfce-first-run.sh" && "$HOME/.config/xfce-first-run.sh" || true'
Hidden=false
NoDisplay=true
X-GNOME-Autostart-enabled=true
FIRSTRUN

info "Creating Firefox safe wrapper. Firefox + VirGL/WebGL is currently unstable on aarch64/virpipe."
FF_SAFE_PROFILE="$HOME/.mozilla/firefox/kirin-safe"
mkdir -p "$FF_SAFE_PROFILE"
cat > "$FF_SAFE_PROFILE/user.js" <<'FFPREFS'
user_pref("webgl.disabled", true);
user_pref("webgl.force-enabled", false);
user_pref("gfx.webrender.force-disabled", true);
user_pref("gfx.webrender.software", true);
user_pref("layers.acceleration.disabled", true);
user_pref("media.hardware-video-decoding.enabled", false);
user_pref("media.ffmpeg.vaapi.enabled", false);
user_pref("widget.dmabuf.force-enabled", false);
FFPREFS

cat > "$HOME/bin/firefox-safe" <<'FFSAFE'
#!/data/data/com.termux/files/usr/bin/bash
# Run Firefox without VirGL/Zink/WebGL. This is intentional: Firefox currently
# can crash the whole Termux:X11 session on VirGL/Mali/Maleoon.
unset MESA_LOADER_DRIVER_OVERRIDE VK_ICD_FILENAMES TU_DEBUG ZINK_DESCRIPTORS MESA_VK_WSI_PRESENT_MODE
export LIBGL_ALWAYS_SOFTWARE=1
export GALLIUM_DRIVER=llvmpipe
export MESA_GL_VERSION_OVERRIDE=3.3
export MESA_GLES_VERSION_OVERRIDE=3.0
export MOZ_ENABLE_WAYLAND=0
export MOZ_X11_EGL=0
export MOZ_WEBRENDER=0
export MOZ_ACCELERATED=0
exec firefox -profile "$HOME/.mozilla/firefox/kirin-safe" "$@"
FFSAFE
chmod +x "$HOME/bin/firefox-safe"

cat > "$HOME/.local/share/applications/firefox-safe.desktop" <<EOF2
[Desktop Entry]
Name=Firefox Safe
Comment=Firefox without VirGL/WebGL acceleration for Kirin/Mali stability
Exec=$HOME/bin/firefox-safe %u
Icon=firefox
Type=Application
Categories=Network;WebBrowser;
Terminal=false
EOF2

cat > "$HOME/Desktop/Firefox.desktop" <<EOF2
[Desktop Entry]
Name=Firefox Safe
Exec=$HOME/bin/firefox-safe
Icon=firefox
Type=Application
Terminal=false
EOF2
chmod +x "$HOME/Desktop/Firefox.desktop" 2>/dev/null || true

# Override main Firefox menu entry if present.
if [ -f "$PREFIX/share/applications/firefox.desktop" ]; then
    cp "$PREFIX/share/applications/firefox.desktop" "$HOME/.local/share/applications/firefox.desktop" 2>/dev/null || true
    sed -i "s|^Exec=.*|Exec=$HOME/bin/firefox-safe %u|" "$HOME/.local/share/applications/firefox.desktop" 2>/dev/null || true
    sed -i "s|^Name=.*|Name=Firefox Safe|" "$HOME/.local/share/applications/firefox.desktop" 2>/dev/null || true
fi

info "Creating explicit VirGL test wrappers..."
cat > "$HOME/bin/glxinfo-virgl" <<'GLXINFO'
#!/data/data/com.termux/files/usr/bin/bash
source "$HOME/.config/linux-gpu.sh" 2>/dev/null || true
source "$HOME/.config/termux-gpu-common.sh" 2>/dev/null || true
start_virgl_server 2>/dev/null || true
export DISPLAY="${DISPLAY:-:0}"
exec glxinfo -B "$@"
GLXINFO
chmod +x "$HOME/bin/glxinfo-virgl"

cat > "$HOME/bin/glxgears-virgl" <<'GLXGEARS'
#!/data/data/com.termux/files/usr/bin/bash
source "$HOME/.config/linux-gpu.sh" 2>/dev/null || true
source "$HOME/.config/termux-gpu-common.sh" 2>/dev/null || true
start_virgl_server 2>/dev/null || true
export DISPLAY="${DISPLAY:-:0}"
exec glxgears "$@"
GLXGEARS
chmod +x "$HOME/bin/glxgears-virgl"

info "Writing updated start-x11.sh..."
cat > "$HOME/start-x11.sh" <<'STARTX11'
#!/data/data/com.termux/files/usr/bin/bash
set -u

echo ""
echo "=============================================="
echo "  [*] Starting XFCE4 via Termux-X11..."
echo "=============================================="
echo ""

source "$HOME/.config/linux-gpu.sh" 2>/dev/null || true
source "$HOME/.config/termux-gpu-common.sh" 2>/dev/null || true

export USER="${USER:-root}"
export LOGNAME="${LOGNAME:-root}"
export HOSTNAME="android-linux"
export HOST="android-linux"
export NO_AT_BRIDGE=1

# Avoid XFCE restoring Firefox or another GL client from the previous crashed session.
rm -rf "$HOME/.cache/sessions"/* 2>/dev/null || true

stop_virgl_server 2>/dev/null || true
pkill -9 -f "termux.x11" 2>/dev/null || true
pkill -9 -f "Xvnc" 2>/dev/null || true
pkill -9 -f "xfce4-session" 2>/dev/null || true
pkill -9 -f "xfwm4" 2>/dev/null || true
pkill -9 -f "xfdesktop" 2>/dev/null || true
pkill -9 -f "firefox" 2>/dev/null || true
pkill -9 -f "dbus" 2>/dev/null || true
rm -f /tmp/.X0-lock /tmp/.X1-lock /tmp/.X11-unix/X0 /tmp/.X11-unix/X1 2>/dev/null || true

unset PULSE_SERVER
pulseaudio --kill 2>/dev/null || true
sleep 0.5
echo "[*] Starting audio..."
pulseaudio --start --exit-idle-time=-1 2>/dev/null || true
sleep 1
pactl load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1 2>/dev/null || true
export PULSE_SERVER=127.0.0.1

start_virgl_server 2>/dev/null || true

echo "[*] Starting Termux-X11 on :0..."
termux-x11 :0 -ac ${TERMUX_X11_EXTRA_ARGS:-} &
sleep 3
export DISPLAY=:0

# Apply runtime XFCE safety knobs after X exists.
xfconf-query -c xfce4-session -p /general/SaveOnExit -n -t bool -s false 2>/dev/null || true
xfconf-query -c xfwm4 -p /general/use_compositing -n -t bool -s false 2>/dev/null || true

[ -f "$HOME/proot-menu-sync.sh" ] && bash "$HOME/proot-menu-sync.sh" >/dev/null 2>&1 &

echo "----------------------------------------------"
echo "  [*] Open the Termux-X11 app to see desktop"
echo "  [*] Firefox menu entry is patched to Firefox Safe"
echo "  [*] GPU test: glxinfo-virgl / glxgears-virgl"
echo "----------------------------------------------"
echo ""

if command -v dbus-launch >/dev/null 2>&1; then
    exec dbus-launch --exit-with-session startxfce4
else
    exec startxfce4
fi
STARTX11
chmod +x "$HOME/start-x11.sh"

info "Writing software fallback start-x11-safe.sh..."
cat > "$HOME/start-x11-safe.sh" <<'STARTSAFE'
#!/data/data/com.termux/files/usr/bin/bash
set -u

echo ""
echo "=============================================="
echo "  [*] Starting XFCE4 via Termux-X11 / SOFTWARE"
echo "=============================================="
echo ""

source "$HOME/.config/termux-gpu-common.sh" 2>/dev/null || true
stop_virgl_server 2>/dev/null || true

export LIBGL_ALWAYS_SOFTWARE=1
export GALLIUM_DRIVER=llvmpipe
export MESA_GL_VERSION_OVERRIDE=3.3
export MESA_GLES_VERSION_OVERRIDE=3.0
export LIBGL_DRI3_DISABLE=1
unset MESA_LOADER_DRIVER_OVERRIDE VK_ICD_FILENAMES TU_DEBUG ZINK_DESCRIPTORS MESA_VK_WSI_PRESENT_MODE
export NO_AT_BRIDGE=1

rm -rf "$HOME/.cache/sessions"/* 2>/dev/null || true
pkill -9 -f "termux.x11" 2>/dev/null || true
pkill -9 -f "xfce4-session" 2>/dev/null || true
pkill -9 -f "firefox" 2>/dev/null || true
pkill -9 -f "dbus" 2>/dev/null || true
rm -f /tmp/.X0-lock /tmp/.X11-unix/X0 2>/dev/null || true

termux-x11 :0 -ac ${TERMUX_X11_EXTRA_ARGS:-} &
sleep 3
export DISPLAY=:0

if command -v dbus-launch >/dev/null 2>&1; then
    exec dbus-launch --exit-with-session startxfce4
else
    exec startxfce4
fi
STARTSAFE
chmod +x "$HOME/start-x11-safe.sh"

info "Writing updated stop-linux.sh..."
cat > "$HOME/stop-linux.sh" <<'STOPLINUX'
#!/data/data/com.termux/files/usr/bin/bash
echo "Stopping all sessions..."
source "$HOME/.config/termux-gpu-common.sh" 2>/dev/null || true
stop_virgl_server 2>/dev/null || true
pkill -9 -f "termux.x11" 2>/dev/null || true
vncserver -kill :1 2>/dev/null || true
pkill -9 -f "Xvnc" 2>/dev/null || true
pkill -9 -f "pulseaudio" 2>/dev/null || true
pkill -9 -f "xfce4-session" 2>/dev/null || true
pkill -9 -f "xfwm4" 2>/dev/null || true
pkill -9 -f "xfdesktop" 2>/dev/null || true
pkill -9 -f "firefox" 2>/dev/null || true
pkill -9 -f "dbus" 2>/dev/null || true
rm -f /tmp/.X0-lock /tmp/.X1-lock /tmp/.X11-unix/X0 /tmp/.X11-unix/X1 \
      "${TMPDIR:-/data/data/com.termux/files/usr/tmp}"/.virgl_test \
      "${TMPDIR:-/data/data/com.termux/files/usr/tmp}"/virgl_test* 2>/dev/null || true
echo "Done."
STOPLINUX
chmod +x "$HOME/stop-linux.sh"

ok "Hotfix installed. Start with: bash ~/start-x11.sh"
warn "If it still crashes, run: TERMUX_VIRGL_BACKEND=plain bash ~/start-x11.sh"
warn "Last-resort stable mode: bash ~/start-x11-safe.sh"
warn "VirGL log: cat \${TMPDIR:-/data/data/com.termux/files/usr/tmp}/virgl-kirin.log"
